
The Drought Severity Workflow (DSW) is built using individal drought indicators and brings them together using the Combined Drought Indicator (CDI) developed by Sepulcre-Canto et al., 2012).

==== Drought Indicator Descriptions
The Drought Indicator API may be used to obtain any of the following indicators for a given latitude, longitude and time period. If a single latitude and longitude are provided, data for a single point will be returned. If two latitdudes and longitudes are provided, data within a bounding box cornered by the latitude and longitude values will be returned. If three or more latitude and longitude values are provided, data within a polygon will be returned.

_Standardised Precipitation Index_

The Standardised Precipitation Index (SPI) is a statistical value describing the amount of rainfall in a given time period relative to a longer time period for a given location. The SPI is a common drought indicator and provides an early warning of an impending drought. SPI is computed in monthly time intervals. The SPI can be obtained directly from the Global Drought Observatory (GDO) or computed using total precipitation from the ERA5 reanalysis from ECMWF.

_Soil Moisture Anomaly_

The Soil Moisture Anomaly (SMA) is another common indicator for agricultural drought, as it results from prolonged lack of rainfall and can precede poor vegetation health. A surface SMA can be obtained from satellite data, or the SMA at greater depths into the soil from reanalyses or models. The SMA is computed relative to a long-term baseline period for a given location and is provided at a frequency of dekads. The SMA can be obtained directly from the Global Drought Observatory (GDO) or computed using soil water volume from the ERA5 reanalysis from ECMWF.The ERA5 data is available for 4 different soil levels.

_Fraction of Absorbed Photosynthetically Active Radiation_

The fraction of Absorbed Photosynthetically Active Radiation (fAPAR) is a satellite-derived value describing the proportion of solar radiation used directly by plants for growth and provides an indication of plant health. A drawback of using fAPAR as a drought indicator is that lower values can result from non-drought related events, such as disease. The fAPAR anomaly is computed relative to a long-term baseline period for a given location and is provided at a freqency of dekads. The fAPAR is obtained from GDO only.

_The Combined Drought Indicator_

The Combined Drought Indicator (CDI, Sepulcre-Canto et al., 2012) provides an accessible measure of agricultural drought severity by assigning a Normal, Watch, Warning or Alert status to a particular region at a particular time. This allows a user without intimate knowledge of drought indicators to understand the current situation and take appropriate action.

The CDI is computed by combining statistical measures of precipitation (SPI), soil moisture (SMA) and vegetation health (FAPAR). <<Table 1>> shows how these are combined to give the different statuses. As an example, if the SPI, SMA and fAPAR are -1.2, 0.7, and -0.9 respectively, the CDI level would be 'Watch'. If all three are below -1, the CDI would be 'Alert 1'.

[%unnumbered]
.Combined Drought Indicator statuses, adapted from Sepulcre-Canto et al. (2012)
[width=100%,options="header"]
[cols="18h,~,10,10,10"]
|====================
|CDI    |Description      |SPI  |SMA  |FAPAR
|Normal |No drought       |     |     | 
|Watch  |Lower than usual rainfall |< -1 |     | 
|Warning|Dry soil following lower than usual rainfall |< -1 |< -1 |
|Alert 1|Vegetation stress following lower than usual rainfall and dry soil|< -1 |< -1 |< -1
|Alert 2|Vegetation stress following lower than usual rainfall (soil unaffected). |< -1 |     |< -1

|====================

References

* Cammalleri C, Micale F, Vogt J. A novel soil moisture-based drought severity index (DSI) combining water deficit magnitude and frequency. Hydrological Processes, 30(2), pp. 289-301. JRC96439. (2016). https://hess.copernicus.org/articles/21/6329/2017/

* Sepulcre-Canto, G., Horizon, S., Singleton, A., Carrao, H. and Vogt, J. Development of a Combined Drought Indicator to detect agricultural drought in Europe. Nat. Hazards Earth Syst. Sci., 12, pp. 3519–3531. (2012). doi:10.5194/nhess-12-3519-2012

